from PySide6.QtCore import (QCoreApplication,QMetaObject, QRect,QSize)
from PySide6.QtGui import (QFont, QPixmap, QDoubleValidator)
from PySide6.QtWidgets import (QComboBox, QWidget, QFrame, QGroupBox, QHBoxLayout, QLabel, QLineEdit, QPushButton, QVBoxLayout, QDialog)
class Ui_MMMUi(object):
    def setupUi(self, MMMUi):
        if not MMMUi.objectName():
            MMMUi.setObjectName(u"MMMUi")
        MMMUi.resize(1023, 723)
        MMMUi.setMaximumSize(QSize(1023, 723))
        MMMUi.setStyleSheet(u"\n"
"background-color: rgb(63, 63, 63);")
        self.Title = QFrame(MMMUi)
        self.Title.setObjectName(u"Title")
        self.Title.setGeometry(QRect(-1, 0, 1021, 91))
        self.verticalLayout_7 = QVBoxLayout(self.Title)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(220, 0, 60, 0)
        self.Title1 = QFrame(self.Title)
        self.Title1.setObjectName(u"Title1")
        self.verticalLayout_10 = QVBoxLayout(self.Title1)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.verticalLayout_10.setContentsMargins(75, 0, 0, 0)
        self.Title1_2 = QLabel(self.Title1)
        self.Title1_2.setObjectName(u"Title1_2")
        font = QFont()
        font.setFamilies([u"Segoe UI Black"])
        font.setPointSize(18)
        font.setBold(True)
        self.Title1_2.setFont(font)
        self.Title1_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.verticalLayout_10.addWidget(self.Title1_2)
        self.verticalLayout_7.addWidget(self.Title1)
        self.Title2 = QFrame(self.Title)
        self.Title2.setObjectName(u"Title2")
        self.verticalLayout_9 = QVBoxLayout(self.Title2)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.verticalLayout_9.setContentsMargins(0, 0, -1, 0)
        self.Title2_2 = QLabel(self.Title2)
        self.Title2_2.setObjectName(u"Title2_2")
        self.Title2_2.setFont(font)
        self.Title2_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.verticalLayout_9.addWidget(self.Title2_2)
        self.verticalLayout_7.addWidget(self.Title2)
        self.Input_and_Plots = QFrame(MMMUi)
        self.Input_and_Plots.setObjectName(u"Input_and_Plots")
        self.Input_and_Plots.setGeometry(QRect(-1, 91, 1021, 641))
        self.Input = QGroupBox(self.Input_and_Plots)
        self.Input.setObjectName(u"Input")
        self.Input.setGeometry(QRect(10, 0, 371, 621))
        self.Input.setStyleSheet(u"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 50, 50);")
        self.verticalLayout_3 = QVBoxLayout(self.Input)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.TransmittanceImage = QLabel(self.Input)
        self.TransmittanceImage.setObjectName(u"TransmittanceImage")
        self.TransmittanceImage.setMaximumSize(QSize(469, 95))
        self.TransmittanceImage.setPixmap(QPixmap(u"trans.png"))
        self.TransmittanceImage.setScaledContents(True)
        self.verticalLayout_3.addWidget(self.TransmittanceImage)
        self.Transmittance_Input = QGroupBox(self.Input)
        self.Transmittance_Input.setObjectName(u"Transmittance_Input")
        font1 = QFont()
        font1.setFamilies([u"Segoe UI Black"])
        font1.setPointSize(10)
        font1.setBold(True)
        self.Transmittance_Input.setFont(font1)
        self.Transmittance_Input.setStyleSheet(u"border-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.verticalLayout = QVBoxLayout(self.Transmittance_Input)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.validator = QDoubleValidator(-9999, 9999, 2)
        #a
        self.aInput = QFrame(self.Transmittance_Input)
        self.aInput.setObjectName(u"aInput")
        self.horizontalLayout_2 = QHBoxLayout(self.aInput)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        #a0
        self.a0Label = QLabel(self.aInput)
        self.a0Label.setObjectName(u"a0Label")
        font2 = QFont()
        font2.setFamilies([u"Source Code Pro"])
        font2.setPointSize(14)
        font2.setBold(True)
        self.a0Label.setFont(font2)
        self.horizontalLayout_2.addWidget(self.a0Label)
        self.a0Input = QLineEdit(self.aInput)
        self.a0Input.setObjectName(u"a0Input")
        self.a0Input.setMaximumSize(QSize(176, 20))
        self.a0Input.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
                                   "color: rgb(0, 0, 0);")
        self.a0Input.setText("0")
        self.a0Input.setValidator(self.validator)
        self.horizontalLayout_2.addWidget(self.a0Input)
        #a1
        self.a1Label = QLabel(self.aInput)
        self.a1Label.setObjectName(u"a1Label")
        self.a1Label.setFont(font2)
        self.horizontalLayout_2.addWidget(self.a1Label)
        self.a1Input = QLineEdit(self.aInput)
        self.a1Input.setObjectName(u"a1Input")
        self.a1Input.setMaximumSize(QSize(176, 20))
        self.a1Input.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.a1Input.setText("0")
        self.a1Input.setValidator(self.validator)
        self.horizontalLayout_2.addWidget(self.a1Input)
        self.verticalLayout.addWidget(self.aInput)
        #b
        self.bInput = QFrame(self.Transmittance_Input)
        self.bInput.setObjectName(u"bInput")
        self.horizontalLayout_3 = QHBoxLayout(self.bInput)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        #b2
        self.b2Label = QLabel(self.bInput)
        self.b2Label.setObjectName(u"b2Label")
        self.b2Label.setFont(font2)
        self.horizontalLayout_3.addWidget(self.b2Label)
        self.b2Input = QLineEdit(self.bInput)
        self.b2Input.setObjectName(u"b2Input")
        self.b2Input.setMaximumSize(QSize(102, 19))
        self.b2Input.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.b2Input.setValidator(self.validator)
        self.b2Input.setText("0")
        self.horizontalLayout_3.addWidget(self.b2Input)
        #b1
        self.b1Label = QLabel(self.bInput)
        self.b1Label.setObjectName(u"b1Label")
        self.b1Label.setFont(font2)
        self.horizontalLayout_3.addWidget(self.b1Label)
        self.b1Input = QLineEdit(self.bInput)
        self.b1Input.setObjectName(u"b1Input")
        self.b1Input.setMaximumSize(QSize(102, 19))
        self.b1Input.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.b1Input.setValidator(self.validator)
        self.b1Input.setText("0")
        self.horizontalLayout_3.addWidget(self.b1Input)
        #b0
        self.b0Label = QLabel(self.bInput)
        self.b0Label.setObjectName(u"b0Label")
        self.b0Label.setFont(font2)
        self.horizontalLayout_3.addWidget(self.b0Label)
        self.b0Input = QLineEdit(self.bInput)
        self.b0Input.setObjectName(u"b0Input")
        self.b0Input.setMaximumSize(QSize(102, 16777215))
        self.b0Input.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.b0Input.setText("0")
        self.b0Input.setValidator(self.validator)
        self.horizontalLayout_3.addWidget(self.b0Input)
        self.verticalLayout.addWidget(self.bInput)
        self.verticalLayout_3.addWidget(self.Transmittance_Input)
        self.PiImage = QLabel(self.Input)
        self.PiImage.setObjectName(u"PiImage")
        self.PiImage.setMaximumSize(QSize(400, 100))
        self.PiImage.setPixmap(QPixmap(u"PI.png"))
        self.PiImage.setScaledContents(True)
        self.verticalLayout_3.addWidget(self.PiImage)
        self.Pi_Input = QGroupBox(self.Input)
        self.Pi_Input.setObjectName(u"Pi_Input")
        self.Pi_Input.setFont(font1)
        self.Pi_Input.setStyleSheet(u"border-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.verticalLayout_2 = QVBoxLayout(self.Pi_Input)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        #k
        self.KInput = QFrame(self.Pi_Input)
        self.KInput.setObjectName(u"KInput")
        self.horizontalLayout_4 = QHBoxLayout(self.KInput)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.Klabel = QLabel(self.KInput)
        self.Klabel.setObjectName(u"Klabel")
        font3 = QFont()
        font3.setFamilies([u"Segoe UI Black"])
        font3.setPointSize(11)
        font3.setBold(True)
        self.Klabel.setFont(font3)
        self.horizontalLayout_4.addWidget(self.Klabel)
        self.Kinput = QLineEdit(self.KInput)
        self.Kinput.setObjectName(u"Kinput")
        self.Kinput.setMaximumSize(QSize(293, 30))
        self.Kinput.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.Kinput.setText("0")
        self.Kinput.setValidator(self.validator)
        self.horizontalLayout_4.addWidget(self.Kinput)
        self.verticalLayout_2.addWidget(self.KInput)
        #Ti
        self.TimeInput = QFrame(self.Pi_Input)
        self.TimeInput.setObjectName(u"TimeInput")
        self.horizontalLayout_5 = QHBoxLayout(self.TimeInput)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.TimeLabel = QLabel(self.TimeInput)
        self.TimeLabel.setObjectName(u"TimeLabel")
        self.TimeLabel.setFont(font3)
        self.horizontalLayout_5.addWidget(self.TimeLabel)
        self.TimeInput_2 = QLineEdit(self.TimeInput)
        self.TimeInput_2.setObjectName(u"TimeInput_2")
        self.TimeInput_2.setMaximumSize(QSize(288, 19))
        self.TimeInput_2.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.TimeInput_2.setText("0")
        self.TimeInput_2.setValidator(self.validator)
        self.horizontalLayout_5.addWidget(self.TimeInput_2)
        self.verticalLayout_2.addWidget(self.TimeInput)
        self.verticalLayout_3.addWidget(self.Pi_Input)
        self.InputSignal_Input = QGroupBox(self.Input)
        self.InputSignal_Input.setObjectName(u"InputSignal_Input")
        self.InputSignal_Input.setStyleSheet(u"border-color: rgb(0, 0, 0);")
        self.horizontalLayout = QHBoxLayout(self.InputSignal_Input)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.InputSignal_Input_2 = QWidget(self.InputSignal_Input)
        self.InputSignal_Input_2.setObjectName(u"InputSignal_Input_2")
        self.InputSignal_Input_2.setStyleSheet(u"")
        self.verticalLayout_8 = QVBoxLayout(self.InputSignal_Input_2)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.InputSignalChoice = QFrame(self.InputSignal_Input_2)
        self.InputSignalChoice.setObjectName(u"InputSignalChoice")
        self.InputSignalChoice.setFrameShape(QFrame.StyledPanel)
        self.InputSignalChoice.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_9 = QHBoxLayout(self.InputSignalChoice)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.InputSignalChoiceLabel = QLabel(self.InputSignalChoice)
        self.InputSignalChoiceLabel.setObjectName(u"InputSignalChoiceLabel")
        self.InputSignalChoiceLabel.setFont(font1)
        self.InputSignalChoiceLabel.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.horizontalLayout_9.addWidget(self.InputSignalChoiceLabel)
        self.InputSignalChoice_2 = QComboBox(self.InputSignalChoice)
        self.InputSignalChoice_2.addItem("")
        self.InputSignalChoice_2.addItem("")
        self.InputSignalChoice_2.addItem("")
        self.InputSignalChoice_2.setObjectName(u"InputSignalChoice_2")
        font4 = QFont()
        font4.setFamilies([u"Segoe UI Black"])
        font4.setBold(True)
        self.InputSignalChoice_2.setFont(font4)
        self.InputSignalChoice_2.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"border: 0.5px solid white;\n"
"")
        self.InputSignalChoice_2.setFrame(True)
        self.horizontalLayout_9.addWidget(self.InputSignalChoice_2)
        self.verticalLayout_8.addWidget(self.InputSignalChoice)
        #A
        self.AmplittudeInput = QFrame(self.InputSignal_Input_2)
        self.AmplittudeInput.setObjectName(u"AmplittudeInput")
        self.AmplittudeInput.setFrameShape(QFrame.StyledPanel)
        self.AmplittudeInput.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_6 = QHBoxLayout(self.AmplittudeInput)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.AmplitudeLabel = QLabel(self.AmplittudeInput)
        self.AmplitudeLabel.setObjectName(u"AmplitudeLabel")
        self.AmplitudeLabel.setFont(font1)
        self.AmplitudeLabel.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.horizontalLayout_6.addWidget(self.AmplitudeLabel)
        self.AmplitudeInput = QLineEdit(self.AmplittudeInput)
        self.AmplitudeInput.setObjectName(u"AmplitudeInput")
        self.AmplitudeInput.setMaximumSize(QSize(288, 19))
        self.AmplitudeInput.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.AmplitudeInput.setText("0")
        self.AmplitudeInput.setValidator(self.validator)
        self.horizontalLayout_6.addWidget(self.AmplitudeInput)
        self.verticalLayout_8.addWidget(self.AmplittudeInput)
        #F
        self.FrequencyInput = QFrame(self.InputSignal_Input_2)
        self.FrequencyInput.setObjectName(u"FrequencyInput")
        self.FrequencyInput.setFrameShape(QFrame.StyledPanel)
        self.FrequencyInput.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_7 = QHBoxLayout(self.FrequencyInput)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.FrequencyLabel = QLabel(self.FrequencyInput)
        self.FrequencyLabel.setObjectName(u"FrequencyLabel")
        self.FrequencyLabel.setFont(font1)
        self.FrequencyLabel.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.horizontalLayout_7.addWidget(self.FrequencyLabel)
        self.FrequencyInput_2 = QLineEdit(self.FrequencyInput)
        self.FrequencyInput_2.setObjectName(u"FrequencyInput_2")
        self.FrequencyInput_2.setMaximumSize(QSize(288, 19))
        self.FrequencyInput_2.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.FrequencyInput_2.setText("0")
        self.FrequencyInput_2.setValidator(self.validator)
        self.horizontalLayout_7.addWidget(self.FrequencyInput_2)
        self.verticalLayout_8.addWidget(self.FrequencyInput)
        self.horizontalLayout.addWidget(self.InputSignal_Input_2)
        self.verticalLayout_3.addWidget(self.InputSignal_Input)
        #plots
        self.Plots = QFrame(self.Input_and_Plots)
        self.Plots.setObjectName(u"Plots")
        self.Plots.setGeometry(QRect(390, 0, 621, 601))
        self.verticalLayout_4 = QVBoxLayout(self.Plots)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.Plots1 = QFrame(self.Plots)
        self.Plots1.setObjectName(u"Plots1")
        self.Plots1.setStyleSheet(u"border-color: rgb(255, 255, 255);")
        self.Plots1.setFrameShape(QFrame.StyledPanel)
        self.Plots1.setFrameShadow(QFrame.Raised)
        self.verticalLayout_6 = QVBoxLayout(self.Plots1)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.Plot1 = QWidget(self.Plots1)
        self.Plot1.setObjectName(u"Plot1")
        self.Plot1.setMinimumSize(QSize(615, 257))
        self.Plot1.setStyleSheet(u"background-color: rgb(0, 0, 0);\n"
"border: 1.5px solid white;")
        self.verticalLayout_6.addWidget(self.Plot1)
        self.verticalLayout_4.addWidget(self.Plots1)
        self.Plot2 = QFrame(self.Plots)
        self.Plot2.setObjectName(u"Plot2")
        self.Plot2.setFrameShape(QFrame.StyledPanel)
        self.Plot2.setFrameShadow(QFrame.Raised)
        self.verticalLayout_5 = QVBoxLayout(self.Plot2)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.Plot2_2 = QWidget(self.Plot2)
        self.Plot2_2.setObjectName(u"Plot2_2")
        self.Plot2_2.setMinimumSize(QSize(615, 257))
        self.Plot2_2.setStyleSheet(u"background-color: rgb(0, 0, 0);\n"
"border: 1.5px solid white;")
        self.verticalLayout_5.addWidget(self.Plot2_2)
        self.verticalLayout_4.addWidget(self.Plot2)
        #button
        self.SimulateButton = QPushButton(self.Plots)
        self.SimulateButton.setObjectName(u"SimulateButton")
        self.SimulateButton.setMinimumSize(QSize(617, 24))
        self.SimulateButton.setFont(font4)
        self.SimulateButton.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 50, 50);\n"
"border-color: rgb(255, 255, 255);")
        self.SimulateButton.setAutoDefault(False)
        self.verticalLayout_4.addWidget(self.SimulateButton)
        self.dialog=QDialog(MMMUi)
        self.dialog.setWindowTitle("Układ niestabilny, wprowadż poprawne wartości!")
        self.dialog.resize(320,1)
        self.retranslateUi(MMMUi)
        QMetaObject.connectSlotsByName(MMMUi)
    def retranslateUi(self, MMMUi):
        MMMUi.setWindowTitle(QCoreApplication.translate("MMMUi", u"Widget", None))
        self.Title1_2.setText(QCoreApplication.translate("MMMUi", u"Symulacja układu ze sterownikiem PI ", None))
        self.Title2_2.setText(QCoreApplication.translate("MMMUi", u"w konfiguracji z ujemnym sprzężeniem zwrotnym", None))
        self.Input.setTitle("")
        self.TransmittanceImage.setText("")
        self.Transmittance_Input.setTitle(QCoreApplication.translate("MMMUi", u"Parametry układu:", None))
        self.a1Label.setText(QCoreApplication.translate("MMMUi", u"a0:", None))
        self.a0Label.setText(QCoreApplication.translate("MMMUi", u"a1:", None))
        self.b2Label.setText(QCoreApplication.translate("MMMUi", u"b2:", None))
        self.b1Label.setText(QCoreApplication.translate("MMMUi", u"b1:", None))
        self.b0Label.setText(QCoreApplication.translate("MMMUi", u"b0:", None))
        self.PiImage.setText("")
        self.Pi_Input.setTitle(QCoreApplication.translate("MMMUi", u"Parametry sterownika PI:", None))
        self.Klabel.setText(QCoreApplication.translate("MMMUi", u"Wzmocnienie Kp:", None))
        self.TimeLabel.setText(QCoreApplication.translate("MMMUi", u"Czas zdwojenia Ti:", None))
        self.InputSignal_Input.setTitle("")
        self.InputSignalChoiceLabel.setText(QCoreApplication.translate("MMMUi", u"Sygnał wejściowy:", None))
        self.InputSignalChoice_2.setItemText(0, QCoreApplication.translate("MMMUi", u"Sygnał prostokątny", None))
        self.InputSignalChoice_2.setItemText(1, QCoreApplication.translate("MMMUi", u"Sygnał trójkątny", None))
        self.InputSignalChoice_2.setItemText(2, QCoreApplication.translate("MMMUi", u"Sygnał harmoniczny", None))
        self.AmplitudeLabel.setText(QCoreApplication.translate("MMMUi", u"Amplituda:", None))
        self.FrequencyLabel.setText(QCoreApplication.translate("MMMUi", u"Ilość przebiegów:", None))
        self.SimulateButton.setText(QCoreApplication.translate("MMMUi", u"Symuluj", None))